//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasto
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string descripcion { get; set; }
        public decimal monto { get; set; }
        public int id_empleado { get; set; }
        public int id_departamento { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
